# Generated by Django 4.1.9 on 2023-05-24 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_alter_stocktransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
