# Generated by Django 4.1.9 on 2023-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0005_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
