# Generated by Django 4.1.9 on 2023-05-24 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0006_portfolio_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
