# Generated by Django 4.1.9 on 2023-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0007_alter_stocktransaction_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
