# Generated by Django 4.1.9 on 2023-05-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0009_verificationmodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationModel',
        ),
    ]
